CREATE TABLE `assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`steamAppId` int NOT NULL,
	`gameName` varchar(512) NOT NULL,
	`steamData` json,
	`steamSpyData` json,
	`reviewStats` json,
	`headerImage` text,
	`developer` varchar(512),
	`publisher` varchar(512),
	`genres` varchar(512),
	`tags` text,
	`price` varchar(64),
	`releaseDate` varchar(64),
	`platforms` varchar(128),
	`languages` text,
	`totalReviews` int,
	`positiveRate` int,
	`owners` varchar(128),
	`ccu` int,
	`chinaPlayerPercent` varchar(32),
	`hasSimplifiedChinese` int DEFAULT 0,
	`chinaMarketEntry` json,
	`isbnRegulatory` json,
	`crossPlatformPorting` json,
	`marketingStrategy` json,
	`omniChannel` json,
	`businessModel` json,
	`scoreMarketEntry` int,
	`scoreIsbn` int,
	`scorePorting` int,
	`scoreMarketing` int,
	`scoreChannel` int,
	`scoreBusinessModel` int,
	`overallGrade` varchar(8),
	`status` enum('pending','fetching','analyzing','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessments_id` PRIMARY KEY(`id`)
);
